/* Plain-English definitions for Data editor fields. Lookup order: "<dataset>.<field>", then "<field>".
   Workload default fields reuse the input-panel tooltips. */
(function () {
  const TC = window.TC;
  const H = {
    // ---- shared
    id: 'Internal identifier used to link records (e.g. a server\'s gpu_id points at a GPU id). Lowercase, no spaces; keep it stable once other records refer to it.',
    name: 'Display name shown in the app and exports.',
    vendor: 'Manufacturer. Used for the Server vendor filter and vendor-neutral labels.',
    note: 'Free-text note shown with the record — caveats, what to confirm, where a number came from.',
    source: 'Where this value came from (web page, datasheet, quote reference, benchmark run). Shown in the math panels.',
    as_of: 'Date the value was checked or measured (YYYY-MM-DD).',
    status: 'estimate = from a public source on the as-of date · placeholder = low confidence, replace it · override = edited in this browser.',
    feed: 'Tells the daily price job where to read this price automatically. Remove it to maintain the price by hand. Formats are listed in the admin guide.',
    provider: 'Company that sells this API or GPU rental.',
    gpu_id: 'Which GPU this record refers to (links to the GPUs dataset).',
    tier: 'Automatic price feed: the provider’s size-based price tier to read (e.g. "More than 16B parameters").',
    mode: 'Automatic price feed: mirror = the row is the provider’s own list price, checked via OpenRouter · own = OpenRouter’s own price.',
    region: 'Automatic price feed: the cloud region whose published price is read (e.g. eastus2).',
    machine: 'Automatic price feed: the cloud machine type whose price is read (e.g. a3-highgpu-8g).',
    on_demand: 'Automatic price feed: which published column to use as the on-demand price (price or flex).',
    vram: 'Automatic price feed: GPU memory size used to find the right row on the provider’s page (e.g. 80 GB).',
    model: 'Automatic price feed: the model name as written in the provider’s price table.',
    column: 'Automatic price feed: which column of the provider’s price table to read (0 = first model, 1 = second).',
    'gpus.sku': 'Automatic price feed: the provider’s VM/instance SKU whose price is read (e.g. Standard_ND96isr_H100_v5).',

    // ---- models
    'models.family': 'Model family or publisher (Meta Llama, Qwen, Mistral, OpenAI, Anthropic…). Informational.',
    'models.self_hostable': 'Ticked = open weights you can run yourself, so it can be sized for on-prem and GPU cloud. Unticked = API-only (GPT, Claude, Gemini) — shown only in the "other models" API table.',
    'models.architecture': 'dense = every parameter is used for every token. moe (mixture of experts) = only some "expert" parameters are active per token, so it is faster than its size suggests but still needs memory for all parameters.',
    'models.params_total_b': 'Total parameters in billions. Drives how much GPU memory the weights need: params × bytes per parameter (FP16 = 2, FP8 = 1, INT4 = 0.5).',
    'models.params_active_b': 'Parameters used per token, in billions. Same as total for dense models; much smaller for MoE. Drives compute per token and the theoretical speed estimate.',
    'models.layers': 'Number of transformer layers (num_hidden_layers in the model\'s config.json). Scales the size of the KV cache.',
    'models.attention_heads': 'Number of attention heads (num_attention_heads). Tensor-parallel sizes must divide this evenly.',
    'models.kv_heads': 'Key/value heads (num_key_value_heads). Models using grouped-query attention have fewer KV heads than attention heads, which shrinks the KV cache.',
    'models.head_dim': 'Size of each attention head (head_dim, or hidden_size ÷ attention heads). Part of the KV-cache size formula.',
    'models.max_context': 'Longest sequence (input + output tokens) the model supports. Requests longer than this are capped.',
    'models.kv_layout': 'How the model stores its attention cache. Changes the KV-cache formula for sliding-window and MLA models.',
    'models.type': 'standard = every layer caches every token · hybrid_sliding = some layers only keep a short window of recent tokens (gpt-oss, Gemma) · mla = compressed "latent" cache (DeepSeek).',
    'models.full_layers': 'Layers that cache the whole sequence (hybrid sliding-window models).',
    'models.sliding_layers': 'Layers that only cache the most recent "window" tokens (hybrid sliding-window models).',
    'models.window': 'Tokens kept by the sliding-window layers.',
    'models.elems_per_token_per_layer': 'MLA models only: numbers stored per token per layer in the compressed cache (DeepSeek V3: kv_lora_rank 512 + rope dim 64 = 576).',
    'models.native_precision': 'The number format the model was released in. Informational.',
    'models.api_prices': 'Pay-per-token prices for this model from each API provider (USD per 1 million tokens).',
    'models.input_per_m': 'Price per 1 million input tokens (the prompt, documents and history you send).',
    'models.output_per_m': 'Price per 1 million output tokens (what the model writes). Usually several times the input price.',
    'models.cached_input_per_m': 'Price per 1 million input tokens served from the provider\'s prompt cache (repeated system prompts or documents). Used with the "cached-input share" input.',
    'models.batch_discount_pct': 'Discount for asynchronous batch requests (results within hours), e.g. 50. Used with the "batch share" input.',

    // ---- GPUs
    'gpus.memory_gb': 'GPU memory (HBM/GDDR) in GB. Must hold the model weights plus the KV cache for in-flight requests.',
    'gpus.mem_bandwidth_tbps': 'Memory bandwidth in terabytes per second. Generating text is usually limited by how fast weights and cache can be read, so this drives the theoretical speed estimate.',
    'gpus.power_kw': 'Maximum power of one GPU in kilowatts (TDP). Informational — server power is set on each server.',
    'gpus.dense_tflops_fp16': 'Peak dense FP16/BF16 compute in teraflops (without sparsity). Used by the theoretical estimate when compute, not memory, is the limit.',
    'gpus.dense_tflops_fp8': 'Peak dense FP8 compute in teraflops. Used for FP8 models on GPUs that support FP8. Leave unset if the GPU has no FP8.',
    'gpus.dense_tflops_fp4': 'Peak dense FP4 compute in teraflops (Blackwell). Informational today.',
    'gpus.street_price_usd': 'Approximate price of one GPU. Only used when a server is priced as "base + GPUs".',
    'gpus.cloud': 'GPU rental offers for this GPU, one per provider and instance type.',
    'gpus.instance': 'The provider\'s instance or VM name (e.g. p5.48xlarge, ND96isr_H100_v5).',
    'gpus.gpus_per_instance': 'GPUs in one instance. Rentals are billed in whole instances, so small workloads may pay for unused GPUs.',
    'gpus.on_demand_per_gpu_hr': 'Pay-as-you-go price per GPU per hour. Multiplied by the "on-demand active hours" input.',
    'gpus.reserved_per_gpu_hr': 'Committed (reserved) price per GPU per hour, billed 24/7. Used when no per-term rates are listed.',
    'gpus.reserved_term': 'What the reserved price commits you to (e.g. 1 year, Capacity Block). Shown next to the price.',
    'gpus.reserved_terms_per_gpu_hr': 'Reserved prices by commitment length in years ("1", "3", "5"). The calculator uses the longest term that fits the comparison term.',
    'gpus.on_demand_label': 'Optional label replacing "On-demand" (e.g. Google\'s Flex-start pricing).',

    // ---- servers
    'servers.sku': 'The vendor\'s server model name.',
    'servers.gpu_id': 'Which GPU this server configuration uses (links to the GPUs dataset).',
    'servers.gpus_per_node': 'GPUs in one server. A model copy never spans servers unless the model is too big for one; costs round up to whole servers.',
    'servers.price_mode': 'all_in = Price USD is the whole configured server · base_plus_gpus = Base price USD + GPUs per node × the GPU\'s street price.',
    'servers.price_usd': 'All-in price for one configured server (chassis, CPUs, memory, networking and GPUs). Replace placeholders with current real-world pricing.',
    'servers.base_price_usd': 'Server price without GPUs — used only when price mode is base_plus_gpus.',
    'servers.power_kw': 'Maximum power draw of the whole server in kilowatts. Multiplied by load factor, PUE, hours and $/kWh for power cost.',
    'servers.rack_units': 'Height in rack units (U). Informational.',

    // ---- benchmarks
    'benchmarks.model_id': 'Which model was tested.',
    'benchmarks.precision': 'Weight precision used in the test (FP16, FP8, INT4). Must match the workload to be used.',
    'benchmarks.tp': 'Tensor-parallel size: GPUs working together on one copy of the model in the test.',
    'benchmarks.pp': 'Pipeline-parallel size: servers one model copy was split across (1 = single server).',
    'benchmarks.engine': 'Inference software used (vLLM, TensorRT-LLM, SGLang…). Results vary a lot by engine.',
    'benchmarks.engine_version': 'Version of the inference engine. Newer versions are often much faster.',
    'benchmarks.input_len': 'Average input (prompt) length in tokens during the test. Compare with the workload\'s input size.',
    'benchmarks.output_len': 'Average output length in tokens during the test.',
    'benchmarks.concurrency': 'Requests in flight at once during the test. Higher concurrency usually gives more total throughput but slower per-request speed.',
    'benchmarks.source_type': 'External / published run, or Pellera lab (validated). Lab results get their own badge on the Compare tab.',
    'benchmarks.aggregate_output_tps': 'Measured output tokens per second across all requests combined, for one model copy. This replaces the theoretical estimate.',
    'benchmarks.per_request_output_tps': 'Measured output tokens per second that each individual request saw. Used to check the speed target can be met.',

    // ---- assumptions
    'assumptions.power': 'Data-center power assumptions.',
    'assumptions.pue': 'Power usage effectiveness: total facility power ÷ IT power. 1.5 means every 1 kW of servers needs 0.5 kW more for cooling and overhead.',
    'assumptions.electricity_usd_per_kwh': 'Price of electricity per kilowatt-hour.',
    'assumptions.load_factor_pct': 'Average server power draw as a % of its maximum. Inference servers rarely run at full power all day.',
    'assumptions.onprem': 'Cost assumptions for owned servers.',
    'assumptions.memory_overhead_pct': 'GPU memory reserved for the inference engine, activations and fragmentation, on top of weights and KV cache.',
    'assumptions.support_pct_per_year': 'Hardware support and warranty per year, as a % of server price.',
    'assumptions.net_storage_mode': 'How networking and storage is estimated: pct_of_servers (a % of server cost) or per_node (a fixed amount per server).',
    'assumptions.net_storage_pct_of_servers': 'Networking fabric, cabling and storage as a % of server cost.',
    'assumptions.net_storage_usd_per_node': 'Networking and storage per server (used when mode is per_node).',
    'assumptions.install_usd_per_node': 'One-time racking, integration and setup services per server.',
    'assumptions.software_usd_per_gpu_per_year': 'Optional software subscription per GPU per year (e.g. vendor AI software suites). Off by default to stay vendor-neutral.',
    'assumptions.ops_fte': 'Share of one engineer\'s time spent running this cluster (e.g. 0.25).',
    'assumptions.ops_fte_cost_usd_per_year': 'Fully loaded yearly cost of one infrastructure engineer.',
    'assumptions.residual_value_pct': 'Resale value of the servers at the end of the term, as a % of their price (credited back).',
    'assumptions.financing_rate_pct_per_year': 'Cost of capital if the purchase is financed (0 = paid in cash).',
    'assumptions.colo_enabled': 'Add colocation (rented data-center space and power) to on-prem costs.',
    'assumptions.colo_usd_per_kw_month': 'Colocation price per committed kilowatt per month.',
    'assumptions.colo_includes_power': 'Ticked = the colocation price already includes electricity, so power cost is not added separately.',
    'assumptions.kw_per_rack': 'Usable power per rack. Used to estimate rack count for colocation.',
    'assumptions.throughput': 'Settings for the theoretical speed estimate (used only when no measured benchmark matches).',
    'assumptions.roofline_bandwidth_efficiency_pct': 'Share of the GPU\'s peak memory bandwidth assumed achievable when generating text. Higher = faster, more optimistic estimate.',
    'assumptions.roofline_compute_efficiency_pct': 'Share of the GPU\'s peak compute assumed achievable (often called MFU). Higher = faster, more optimistic estimate.',
    'assumptions.prefill_warning_ratio': 'Show a warning when input tokens exceed output tokens by more than this ratio (prompt processing then dominates).',
    'assumptions.cloud': 'GPU cloud settings.',
    'assumptions.hours_per_month': 'Hours billed per month for reserved GPUs (730 = 24/7).',
    'assumptions.workload_defaults': 'Starting values for the workload inputs when someone first opens the app or clicks Reset.',
  };

  TC.fieldHelp = function (dataset, key) {
    if (dataset === 'gpus' && /^[1-9]$/.test(key)) return `Reserved price per GPU per hour for a ${key}-year commitment.`;
    return H[dataset + '.' + key] || H[key] || (dataset === 'assumptions' && TC.inputTip ? TC.inputTip(key) : null);
  };
})();
